### ISSUE TITLE
Feature Description Text Not Converting

### ISSUE THREAD

**Issue by Tabbyfip** [CasanovaSekova/dracula-foundry#9]
**Module Version:** v0.3.1.2

**Describe the bug**

The text for Features on a D&D 5e character sheet is still displaying as dark on dark. I was curious if this was strictly on my game's end or if this was able to be reproduced on your side as well. As you can see below, the description text for Arcane Recovery is still dark.

**To Reproduce**
1. Create / Open a D&D 5e Character Sheet.
2. Go to 'Features'
3. Click '+Add' to add a new feature or go to an existing one.
4. Edit the feature to have description text or find one that does.
5. Uncollapse the Feature to show the text by clicking on the name.
6. This is where the Dracula theme + dark text is displayed most prominently.

**Expected behavior**
I expected the Feature Description text to -also- swap to a lighter theme.

**Screenshots**
![exampletext](https://user-images.githubusercontent.com/93576341/147676425-dc00e61c-eeae-4c85-8e1e-cf42484736f0.png)
(The text below Arcane Recovery isn't swapping as I expected it would.)

**Browser:**
 Chrome - Version 96.0.4664.110 (Official Build) (64-bit)

**Foundry Version:** 
Version 9 - Build 238

**Game System:** 
D&D 5e

**Additional context**
I have a sneaking suspicion this might have been something wrong with importing features but this can also be reproduced when making a new feature from scratch. We're using quite a few plugins/mods and I wasn't able to test this on its own by itself so I apologize for that, the primary one I was suspicious of fighting with it was Plutonium when you import D&D 5e classes/items/features more easily.

Sadly I wasn't able and didn't have the time to give a more deep dive into this and happily will if it turns out to be something you can't reproduce on your end. I'll look more into this when I can and trim it down to find conflicts if any, so if you can't reproduce this feel free to comment and close the ticket! I also wasn't able to try to manually change the font color myself when editing the feature but I'll do that as well when I can.

Thank you for your time and I apologize if this is a user error!

**Comment by apriltaoyvr** [comment]
My bad! I missed this one. This is definitely on me and not you. I'll release it in a quick second.
